language: ruby
bundler_args: --without test
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - psql -c 'create database recurring_select_test' -U postgres
script:
  - rspec spec
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
